--[[
	name = 名称
Key = 键
Value = 值
Des = 描述

--]]
local _table = {
	[1] = {	name = [[暴击率]],	Key = [[CirtPercenter]],	Value = 1.5000,	Des = [[暴击率]],},
	[2] = {	name = [[能量球间隔]],	Key = [[IssueBallTime]],	Value = 20,	Des = [[能量球产生间隔(秒)]],},
	[3] = {	name = [[战斗默认时间]],	Key = [[RoomTime]],	Value = 90,	Des = [[单场战斗默认时间]],},
	[4] = {	name = [[每日领取体力次数]],	Key = [[ApCount]],	Value = 30,	Des = [[每日领取体力次数]],},
	[5] = {	name = [[邀请码奖励]],	Key = [[CodeActive]],	Value = {20101,20102,20103,20104,20105},	Des = [[输入好友邀请码奖励]],},
	[6] = {	name = [[神秘商店刷新]],	Key = [[ExRefresh]],	Value = 30,	Des = [[神秘商店刷新花费钻石]],},
	[7] = {	name = [[精灵之魂]],	Key = [[Soul]],	Value = [[将精灵献祭获得，是精灵觉醒的主要材料之一]],	Des = [[精灵之魂的描述]],},
	[8] = {	name = [[竞技场每天免费战斗次数]],	Key = [[ArenaFreeCount]],	Value = 5,	Des = [[每天免费参加竞技场战斗次数]],},
	[9] = {	name = [[竞技场一次挑战冷却时间]],	Key = [[ArenaCD]],	Value = 10,	Des = [[竞技场一次挑战冷却时间（分钟）]],},
	[10] = {	name = [[竞技场中清一分钟CD的精灵石]],	Key = [[CCD]],	Value = 6,	Des = [[竞技场中清2分钟CD的精灵石]],},
	[11] = {	name = [[竞技场VIP4以上购买增幅]],	Key = [[ArenaExCountStep]],	Value = 10,	Des = [[每次递增10个精灵石]],},
	[12] = {	name = [[竞技场VIP4以上购买次数最多精灵石]],	Key = [[ArenaExCoinMax]],	Value = 200,	Des = [[最高精灵石]],},
	[13] = {	name = [[竞技场胜利获得的荣誉点]],	Key = [[ArenaWinHonor]],	Value = 100,	Des = [[竞技场挑战胜利获得的荣誉点]],},
	[14] = {	name = [[竞技场失败获得的荣誉点]],	Key = [[ArenaLoseHonor]],	Value = 50,	Des = [[竞技场挑战失败获得的荣誉点]],},
	[15] = {	name = [[竞技场奖励发放开始时间]],	Key = [[ArenaAwardStartAt]],	Value = 0.8750,	Des = [[这个时间是针对游戏服当地时间]],},
	[16] = {	name = [[竞技场奖励发放结束时间]],	Key = [[ArenaAwardEndAt]],	Value = 0.8958,	Des = [[这个时间是针对游戏服当地时间]],},
	[17] = {	name = [[竞技场奖励发放信件标题]],	Key = [[ArenaRewardTitle]],	Value = [[竞技场排行奖励]],	Des = [[竞技场奖励发放信件标题]],},
	[18] = {	name = [[竞技场奖励发放信件内容]],	Key = [[ArenaRewardContent]],	Value = [[你在竞技场的表现非常精彩，截止今天{1}，你的竞技场排名为{0}名。
特授予你以下奖励]],	Des = [[竞技场奖励发放信件内容]],},
	[19] = {	name = [[宠物十连价格]],	Key = [[Niudan10Cost]],	Value = 2300,	Des = [[宠物十连抽消耗2300精灵石(9折)]],},
	[20] = {	name = [[宠物抽取价格]],	Key = [[NiudanCost]],	Value = 260,	Des = [[抽取一次价格]],},
	[21] = {	name = [[神兽移动速度]],	Key = [[BossAtkSpeed]],	Value = 150,	Des = [[神兽降临的BOSS移动速度]],},
	[22] = {	name = [[玩家初始金币数量]],	Key = [[InitGold]],	Value = 10000,	Des = [[新玩家初始金币数量]],},
	[23] = {	name = [[玩家初始钻石数量]],	Key = [[InitCoin]],	Value = 0,	Des = [[新玩家初始钻石数量]],},
	[24] = {	name = [[宝石解锁等级]],	Key = [[GemUnlockLv]],	Value = 37,	Des = [[宝石解锁等级]],},
	[25] = {	name = [[Boss战持续时间]],	Key = [[BossAtkDuration]],	Value = 15,	Des = [[Boss战持续时间（分）]],},
	[26] = {	name = [[硬币商店刷新花费钻石]],	Key = [[TopStoreRefreshCosts]],	Value = {30,30,30,30,30,30,30,30},	Des = [[到达500精灵石后之后每次刷新都要500精灵石]],},
	[27] = {	name = [[小喇叭消耗钻石数]],	Key = [[BroadcastCost]],	Value = 15,	Des = [[小喇叭消耗钻石数]],},
	[28] = {	name = [[创建公会消耗钻石]],	Key = [[GuildCreate]],	Value = 300,	Des = [[创建公会消耗钻石]],},
	[29] = {	name = [[小喇叭时限]],	Key = [[BroadcastHold]],	Value = 60,	Des = [[小喇叭时限(分)]],},
	[30] = {	name = [[精灵融合消耗金币]],	Key = [[petmixcost]],	Value = 500000,	Des = [[精灵融合消耗金币]],},
	[31] = {	name = [[扭蛋卡获得金币]],	Key = [[niudancardgold]],	Value = 5000,	Des = [[扭蛋卡获得金币]],},
	[32] = {	name = [[扭蛋一次获得金币]],	Key = [[niudan1gold]],	Value = 10000,	Des = [[扭蛋一次获得金币]],},
	[33] = {	name = [[10连获得金币]],	Key = [[niudan10gold]],	Value = 100000,	Des = [[10连获得金币]],},
	[34] = {	name = [[精灵列表数量上限]],	Key = [[PetListLimit]],	Value = 100,	Des = [[精灵列表数量上限]],},
	[35] = {	name = [[每个进化石副本每天挑战次数]],	Key = [[evolvebattletimes]],	Value = 2,	Des = [[每个进化石副本每天挑战次数]],},
	[36] = {	name = [[宝石位置3解锁等级]],	Key = [[GemPlace3Unlocklv]],	Value = 55,	Des = [[在玩家等级55级时解锁]],},
	[37] = {	name = [[宝石位置4解锁等级]],	Key = [[GemPlace4Unlocklv]],	Value = 65,	Des = [[在玩家等级65级时解锁]],},
	[38] = {	name = [[玩家等级上限]],	Key = [[rolelvlimit]],	Value = 95,	Des = [[玩家当前版本等级上限]],},
	[39] = {	name = [[装备卡送金币数量]],	Key = [[zhuangbeigold]],	Value = 3000,	Des = [[装备卡送金币数量]],},
	[40] = {	name = [[装备单抽送金币数量]],	Key = [[zhuangbei1gold]],	Value = 50000,	Des = [[装备单抽送金币数量]],},
	[41] = {	name = [[十连抽送金币数量]],	Key = [[zhuangbei10gold]],	Value = 500000,	Des = [[十连抽送金币数量]],},
	[42] = {	name = [[单抽钻石价格]],	Key = [[zhuangbei1coin]],	Value = 360,	Des = [[单抽钻石价格]],},
	[43] = {	name = [[十连钻石价格]],	Key = [[zhuangbei10coin]],	Value = 3200,	Des = [[十连钻石价格]],},
	[44] = {	name = [[首冲奖励]],	Key = [[firstcostreward]],	Value = {10001,10002,10003,10004,10005},	Des = [[首冲奖励]],},
	[45] = {	name = [[精灵升级引导关卡]],	Key = [[petupguidestage]],	Value = 3,	Des = [[精灵升级引导关卡]],},
	[46] = {	name = [[扭装备消耗装备卡数量]],	Key = [[eqcardnum]],	Value = 10,	Des = [[扭装备消耗装备卡数量]],},
	[47] = {	name = [[体力每次领取点数]],	Key = [[apget]],	Value = 2,	Des = [[体力每次领取点数]],},
	[48] = {	name = [[每日首次装备扭蛋价格]],	Key = [[dailyeqprice]],	Value = 80,	Des = [[每日首次装备扭蛋价格]],},
	[49] = {	name = [[神兽碎片领取所需战斗次数]],	Key = [[BossBattleTimes]],	Value = 5,	Des = [[神兽碎片领取所需战斗次数]],},
	[50] = {	name = [[冲级活动时间设置（天）]],	Key = [[ServerOpenLvTopDays]],	Value = 5,	Des = [[冲级活动时间设置（天）]],},
	[51] = {	name = [[神兽降临战斗CD（分钟）]],	Key = [[BossDownBattleCD]],	Value = 35,	Des = [[神兽降临战斗CD（分钟）]],},
	[52] = {	name = [[进化引导精灵]],	Key = [[EvolvePet]],	Value = 290,	Des = [[进化引导精灵]],},
	[53] = {	name = [[冠军联赛每日挑战次数]],	Key = [[ChampionshipfreeCnt]],	Value = 10,	Des = [[冠军联赛每日挑战次数]],},
	[54] = {	name = [[冠军联赛解锁等级]],	Key = [[ChampionshipLv]],	Value = 37,	Des = [[冠军联赛解锁等级]],},
	[55] = {	name = [[冠军联赛商店第二只精灵ID]],	Key = [[CsSecondPetId]],	Value = 150,	Des = [[冠军联赛商店第二只精灵ID]],},
	[56] = {	name = [[冠军联赛商店第二只精灵购买VIP需求]],	Key = [[CsSecondPetVip]],	Value = 9,	Des = [[冠军联赛商店第二只精灵购买VIP需求]],},
	[57] = {	name = [[冠军联赛对手刷新价格]],	Key = [[CsPlayerRefreshCost]],	Value = 10,	Des = [[冠军联赛对手刷新价格]],},
	[58] = {	name = [[冠军联赛商店刷新价格]],	Key = [[CsShopRefreshCost]],	Value = 30,	Des = [[冠军联赛商店刷新价格]],},
	[59] = {	name = [[冠军联赛复活价格]],	Key = [[CsRecoverCost]],	Value = 100,	Des = [[冠军联赛复活价格]],},
	[60] = {	name = [[冠军之塔扫荡价格]],	Key = [[TopTowerClearCost]],	Value = 100,	Des = [[冠军之塔扫荡价格]],},
	[61] = {	name = [[无尽试炼宝箱购买价格]],	Key = [[AdvBuyBoxCost]],	Value = 50,	Des = [[无尽试炼宝箱购买价格]],},
	[62] = {	name = [[幸运转盘刷新价格]],	Key = [[LuckyRefresh]],	Value = 50000,	Des = [[幸运转盘刷新价格]],},
	[63] = {	name = [[幸运转盘抽一次]],	Key = [[LuckyBuy1]],	Value = 50,	Des = [[幸运转盘抽一次]],},
	[64] = {	name = [[幸运转盘抽10次]],	Key = [[LuckyBuy10]],	Value = 500,	Des = [[幸运转盘抽10次]],},
	[65] = {	name = [[公会战商店刷新钻石消耗]],	Key = [[GuildFightStoreCosts]],	Value = {30,30,30,30,30,30},	Des = [[公会战商店刷新钻石消耗]],},
	[66] = {	name = [[公会战攻击指令描述]],	Key = [[GuildFightAtk]],	Value = [[选定攻击指令后可以对周边据点发动攻击]],	Des = [[公会战攻击指令描述]],},
	[67] = {	name = [[公会战防守指令描述]],	Key = [[GuildFightDef]],	Value = [[选定防守指令后可以增强防守队伍]],	Des = [[公会战防守指令描述]],},
	[68] = {	name = [[公会战支援指令描述]],	Key = [[GuildFightAst]],	Value = [[选定支援指令后可以支援周边据点]],	Des = [[公会战支援指令描述]],},
	[69] = {	name = [[公会战商店刷新时间]],	Key = [[GuildFightStoreRef]],	Value = 21,	Des = [[公会战商店刷新时间]],},
	[70] = {	name = [[公会战CD价格]],	Key = [[GuildFightCDCost]],	Value = 2,	Des = [[公会战CD价格]],},
	[71] = {	name = [[公会战准备阶段起始时间]],	Key = [[GuildFightPreST]],	Value = [[8|00]],	Des = [[公会战准备阶段起始时间]],},
	[72] = {	name = [[公会战准备阶段结束时间]],	Key = [[GuildFightPreET]],	Value = [[18|00]],	Des = [[公会战准备阶段结束时间]],},
	[73] = {	name = [[公会战战斗阶段起始时间]],	Key = [[GuildFightBatST]],	Value = [[21|30]],	Des = [[公会战战斗阶段起始时间]],},
	[74] = {	name = [[公会战战斗阶段结束时间]],	Key = [[GuildFightBatET]],	Value = [[22|00]],	Des = [[公会战战斗阶段结束时间]],},
	[75] = {	name = [[公会战boss挑战价格]],	Key = [[GuildFightBossCost]],	Value = {50,80,120,150,200,200},	Des = [[公会战boss挑战价格]],},
	[76] = {	name = [[小智队伤害系数]],	Key = [[GuildFightBoss1]],	Value = 0.4400,	Des = [[小智队伤害系数]],},
	[77] = {	name = [[小茂队伤害系数]],	Key = [[GuildFightBoss2]],	Value = 0.4100,	Des = [[小茂队伤害系数]],},
	[78] = {	name = [[小霞队伤害系数]],	Key = [[GuildFightBoss3]],	Value = 0.3900,	Des = [[小霞队伤害系数]],},
	[79] = {	name = [[公会战报名价格]],	Key = [[GuildFightSignCost]],	Value = 2000,	Des = [[公会战报名价格]],},
	[80] = {	name = [[公会战公会等级要求]],	Key = [[GuildFightLevelLimit]],	Value = 3,	Des = [[公会战公会等级要求]],},
	[81] = {	name = [[公会战玩家等级要求]],	Key = [[GuildFightUnlockLv]],	Value = 45,	Des = [[公会战玩家等级要求]],},
	[82] = {	name = [[公会战行动力CD]],	Key = [[GuildFightCD]],	Value = 4,	Des = [[公会战行动力CD]],},
	[83] = {	name = [[mega进化5星等级]],	Key = [[Mega5StarLevelLimit]],	Value = 80,	Des = [[mega进化5星等级]],},
	[84] = {	name = [[mega进化5星觉醒等级]],	Key = [[Mega5StarAwakeLimit]],	Value = 24,	Des = [[mega进化5星觉醒等级]],},
	[85] = {	name = [[mega进化6星等级]],	Key = [[Mega6StarLevelLimit]],	Value = 80,	Des = [[mega进化6星等级]],},
	[86] = {	name = [[mega进化6星觉醒等级]],	Key = [[Mega6StarAwakeLimit]],	Value = 20,	Des = [[mega进化6星觉醒等级]],},
	[87] = {	name = [[秘宝消耗金币系数]],	Key = [[MibaoCostGold]],	Value = 200,	Des = [[秘宝消耗金币系数]],},
	[88] = {	name = [[公会战购买次数价格]],	Key = [[GuildFightBuyCost]],	Value = {100,200,400,800,1000,2000},	Des = [[公会战购买次数价格]],},
	[89] = {	name = [[幸运抽奖金额1]],	Key = [[LuckDeposit1]],	Value = 60,	Des = [[LuckDeposit1]],},
	[90] = {	name = [[幸运抽奖金额2]],	Key = [[LuckDeposit2]],	Value = 300,	Des = [[LuckDeposit2]],},
	[91] = {	name = [[幸运抽奖金额3]],	Key = [[LuckDeposit3]],	Value = 500,	Des = [[LuckDeposit3]],},
	[92] = {	name = [[改名消耗精灵石]],	Key = [[RenameCost]],	Value = 100,	Des = [[改名消耗精灵石]],},
	[93] = {	name = [[21点兑换额度1]],	Key = [[21pointExchange1]],	Value = 10,	Des = [[21点兑换额度1]],},
	[94] = {	name = [[21点兑换额度2]],	Key = [[21pointExchange2]],	Value = 100,	Des = [[21点兑换额度2]],},
	[95] = {	name = [[21下注额度1]],	Key = [[21pointCost1]],	Value = 10,	Des = [[21pointCost1]],},
	[96] = {	name = [[21下注额度2]],	Key = [[21pointCost2]],	Value = 100,	Des = [[21pointCost2]],},
	[97] = {	name = [[21下注额度3]],	Key = [[21pointCost3]],	Value = 1000,	Des = [[21pointCost3]],},
	[98] = {	name = [[狩猎场次数]],	Key = [[HuntTimes]],	Value = 10,	Des = [[狩猎场次数]],},
	[99] = {	name = [[草之钥匙来源]],	Key = [[GrassKeySource]],	Des = [[草之钥匙来源]],},
	[100] = {	name = [[电之钥匙来源]],	Key = [[ElectricKeySource]],	Des = [[电之钥匙来源]],},
	[101] = {	name = [[水之钥匙来源]],	Key = [[WaterKeySource]],	Des = [[水之钥匙来源]],},
	[102] = {	name = [[岩之钥匙来源]],	Key = [[StoneKeySource]],	Des = [[岩之钥匙来源]],},
	[103] = {	name = [[火之钥匙来源]],	Key = [[FireKeySource]],	Des = [[火之钥匙来源]],},
	[104] = {	name = [[邀请次数]],	Key = [[HelpTimes]],	Value = 5,	Des = [[邀请次数]],},
	[105] = {	name = [[狩猎场购买价格]],	Key = [[HuntTimePrices]],	Value = {20,20,30,30,30,50,50,50,50,100,100,100},	Des = [[狩猎场购买价格]],},
	[106] = {	name = [[符文重生价格]],	Key = [[RuneRebornCost]],	Value = 200,	Des = [[符文重生价格]],},
	[107] = {	name = [[公会战防守BUFF]],	Key = [[GuildDefBuff]],	Value = 20,	Des = [[公会战防守BUFF]],},
	[108] = {	name = [[公会战防守相连BUFF]],	Key = [[GuildBaseBuff]],	Value = 10,	Des = [[公会战防守相连BUFF]],},
	[109] = {	name = [[羁绊共鸣激活觉醒等级]],	Key = [[PartnerAwake]],	Value = 12,	Des = [[羁绊共鸣激活觉醒等级]],},
	[110] = {	name = [[门票上限]],	Key = [[TicketNum]],	Value = 10,	Des = [[门票上限]],},
	[111] = {	name = [[限时探险召唤精灵消耗]],	Key = [[TLAdvPetCost]],	Value = 30,	Des = [[限时探险召唤精灵消耗]],},
	[112] = {	name = [[限时探险购买次数消耗]],	Key = [[TLAdvBuyCost]],	Value = 30,	Des = [[限时探险购买次数消耗]],},
	[113] = {	name = [[限时探险召唤最低门槛次数]],	Key = [[TLZhaohuan]],	Value = 40,	Des = [[限时探险召唤最低门槛次数]],},
	[114] = {	name = [[命运轮盘钥匙价格]],	Key = [[FateWheelKeyPrice]],	Value = 50,	Des = [[命运轮盘钥匙价格]],},
	[115] = {	name = [[探宝抢夺能量上限]],	Key = [[RobManaLimit]],	Value = 30,	Des = [[探宝抢夺能量上限]],},
	[116] = {	name = [[探宝抢夺能量恢复时间（分钟）]],	Key = [[ManaRecoverTime]],	Value = 30,	Des = [[探宝抢夺能量恢复时间]],},
	[117] = {	name = [[公会战保护时间（分钟）]],	Key = [[GBProtectTime]],	Value = 5,	Des = [[公会战保护时间（分钟）]],},
	[118] = {	name = [[公会宝箱BUFF攻击]],	Key = [[GBBUFFATK]],	Value = 500,	Des = [[公会宝箱BUFF攻击]],},
	[119] = {	name = [[公会宝箱BUFF生命]],	Key = [[GBBUFFHP]],	Value = 500,	Des = [[公会宝箱BUFF生命]],},
	[120] = {	name = [[公会宝箱消耗]],	Key = [[GBBOXCOST]],	Value = 50,	Des = [[公会宝箱消耗]],},
	[121] = {	name = [[公会宝箱描述]],	Key = [[GBDEFAULT]],	Value = [[公会战战斗开战前,每个参战公会成员可开启公会宝箱一次.开启后获得以上奖励,并给全公会的攻击队伍和防守队伍在当天的公会战中额外增加攻击和生命.该加成可以叠加.]],	Des = [[公会宝箱描述]],},
	[122] = {	name = [[公会宝箱奖励]],	Key = [[GBBOXREWARD]],	Value = {28000,28001,28002},	Des = [[公会宝箱奖励]],},
	[123] = {	name = [[遗迹剑增加攻击]],	Key = [[RemainAtk]],	Value = 0.0200,	Des = [[遗迹剑增加攻击]],},
	[124] = {	name = [[遗迹心恢复生命]],	Key = [[RemainHpRecover]],	Value = 0.1500,	Des = [[遗迹心恢复生命]],},
	[125] = {	name = [[遗迹心增加生命]],	Key = [[RemainHp]],	Value = 0.0200,	Des = [[遗迹心增加生命]],},
	[126] = {	name = [[遗迹重置消耗]],	Key = [[RemainReset]],	Value = 300,	Des = [[遗迹重置消耗]],},
	[127] = {	name = [[遗迹炸弹提示]],	Key = [[RemainBoom]],	Value = [[扣除当前10%生命]],	Des = [[遗迹炸弹提示]],},
	[128] = {	name = [[神秘商店礼包1]],	Key = [[MysteryShopGiftReward1]],	Value = {83163,83164,83165,83166},	Des = [[神秘商店礼包内容1]],},
	[129] = {	name = [[神秘商店礼包2]],	Key = [[MysteryShopGiftReward2]],	Value = {83167,83168,83169,83170},	Des = [[神秘商店礼包内容2]],},
	[130] = {	name = [[神秘商店礼包3]],	Key = [[MysteryShopGiftReward3]],	Value = {83171,83172,83173,83174},	Des = [[神秘商店礼包内容3]],},
	[131] = {	name = [[神秘商店礼包4]],	Key = [[MysteryShopGiftReward4]],	Value = {83175,83176,83177,83178},	Des = [[神秘商店礼包内容4]],},
	[132] = {	name = [[神秘商店礼包5]],	Key = [[MysteryShopGiftReward5]],	Value = {83179,83180,83181,83182},	Des = [[神秘商店礼包内容5]],},
	[133] = {	name = [[神秘商店人品值达到多少才可购买对应礼包]],	Key = [[MysteryShopGiftConditions]],	Value = {10,20,30,40,50},	Des = [[列表个数请和礼包个数对应（固定5个）]],},
	[134] = {	name = [[神秘商店出售物品刷新钻石]],	Key = [[MysteryShopRefreshCoin]],	Value = 10,	Des = [[神秘商店出售物品刷新钻石]],},
	[135] = {	name = [[神秘商店礼包对应钻石消耗]],	Key = [[MysteryShopCoins]],	Value = {100,200,300,400,500},	Des = [[神秘商店礼包对应钻石消耗]],},
	[136] = {	name = [[放大镜购买价格]],	Key = [[GlassCost]],	Value = 20,	Des = [[放大镜购买价格]],},
	[137] = {	name = [[放大镜每次购买递增价格]],	Key = [[GlassAddCost]],	Value = 10,	Des = [[放大镜每次购买递增价格]],},
	[138] = {	name = [[装备洗炼消耗价格]],	Key = [[EqCastCost]],	Value = {5,10,15,20},	Des = [[装备洗炼消耗价格]],},
	[139] = {	name = [[装备鉴定消耗价格]],	Key = [[EqIdentifyCost]],	Value = {5,10,15,20},	Des = [[装备鉴定消耗价格]],},
	[140] = {	name = [[装备转移价格]],	Key = [[EqExchangeCost]],	Value = 100,	Des = [[装备转移价格]],},
	[141] = {	name = [[装备还原价格]],	Key = [[EqRestoreCost]],	Value = 20,	Des = [[装备还原价格]],},
	[142] = {	name = [[新手邀请码奖励]],	Key = [[JuniorReward]],	Value = {10006,10007,10008,10009},	Des = [[新手邀请码奖励]],},
	[143] = {	name = [[老玩家回归礼包]],	Key = [[SeniorReward]],	Value = {10010,10011,10012},	Des = [[老玩家回归礼包]],},
	[144] = {	name = [[邀请码礼包说明]],	Key = [[JuniorRewardDes]],	Value = 15,	Des = [[15级前输入邀请码可兑换 金币*30000 精灵石*20 扭蛋卡*10 精灵之魂*50]],},
	[145] = {	name = [[符文合成价格]],	Key = [[RuneMixCost]],	Value = 200,	Des = [[符文合成价格]],},
	[146] = {	name = [[黑名单数量上限]],	Key = [[BlackListLimit]],	Value = 30,	Des = [[黑名单数量上限]],},
}

return _table
