--[[
	ID = 顺序ID
CID = 唯一ID
PetID = 精灵ID
Content = 剧情内容
Type = 表情
Sound = 语音

--]]
local _table = {
	[1] = {	ID = 1,	CID = 1,	PetID = 30,	Content = [[又跟丢了！]],	Type = 0,	Sound = 0,},
	[2] = {	ID = 2,	CID = 2,	PetID = 67,	Content = [[让你不要走太快，肯定是被她发现了。]],	Type = 0,	Sound = 0,},
	[3] = {	ID = 3,	CID = 3,	PetID = 30,	Content = [[你说什么？不是你们慢慢腾腾的，能让她给跑了吗？]],	Type = 0,	Sound = 0,},
	[4] = {	ID = 4,	CID = 101,	PetID = 74,	Content = [[闭嘴！抓不到的话，我们拿什么给首领交差！白痴！]],	Type = 0,	Sound = 0,},
	[5] = {	ID = 5,	CID = 4,	PetID = 150,	Content = [[又是来抓我的，你们在门口取号排队了吗？]],	Type = 0,	Sound = 0,},
	[6] = {	ID = 6,	CID = 5,	PetID = 67,	Content = [[别躲躲藏藏的给我出来！混蛋！]],	Type = 0,	Sound = 0,},
	[7] = {	ID = 7,	CID = 6,	PetID = 30,	Content = [[你终于肯现身啦。]],	Type = 0,	Sound = 0,},
	[8] = {	ID = 8,	CID = 7,	PetID = 74,	Content = [[少废话，给我上！]],	Type = 0,	Sound = 0,},
	[9] = {	ID = 9,	CID = 102,	PetID = 67,	Content = [[哇！]],	Type = 0,	Sound = 0,},
	[10] = {	ID = 10,	CID = 8,	PetID = 150,	Content = [[滚。]],	Type = 0,	Sound = 0,},
	[11] = {	ID = 11,	CID = 9,	PetID = 150,	Content = [[现在才来。要不是刚才的几个杂碎陪我解闷，我早就走了。]],	Type = 1,	Sound = 0,},
	[12] = {	ID = 12,	CID = 10,	PetID = 243,	Content = [[超梦！你今天逃不掉了！]],	Type = 0,	Sound = [[htp_12.mp3]],},
	[13] = {	ID = 13,	CID = 11,	PetID = 150,	Content = [[这个肮脏的世界还值得你们留念吗？我将抹灭它，创造属于我的世界！]],	Type = 0,	Sound = [[htp_13.mp3]],},
	[14] = {	ID = 14,	CID = 12,	PetID = 243,	Content = [[这是我们最后的机会！绝不能让她的阴谋得逞！]],	Type = 0,	Sound = [[htp_14.mp3]],},
	[15] = {	ID = 15,	CID = 13,	PetID = 78,	Content = [[防御型敌人？对付他们是我的专长，看我的！]],	Type = 0,	Sound = 0,},
	[16] = {	ID = 16,	CID = 14,	PetID = 292,	Content = [[你们这些可笑的法术根本无法突破我完美的防御！]],	Type = 0,	Sound = 0,},
	[17] = {	ID = 17,	CID = 15,	PetID = 243,	Content = [[又来了个不怕死的。你永远不会有靠近我的机会！让你们看看什么叫做精确的远程打击！]],	Type = 0,	Sound = 0,},
	[18] = {	ID = 18,	CID = 16,	PetID = 385,	Content = [[受伤了吗？请放心，我会治疗你们的。]],	Type = 0,	Sound = 0,},
	[19] = {	ID = 19,	CID = 17,	PetID = 150,	Content = [[够了！我已经给过你们机会了！现在，面对我的终极力量吧！世间万物，将彻底毁灭！]],	Type = 0,	Sound = [[htp_battle_05.mp3]],},
	[20] = {	ID = 20,	CID = 18,	PetID = 150,	Content = [[你们阻止不了我！黑暗将吞噬一切！]],	Type = 0,	Sound = [[htp_battle_06.mp3]],},
	[21] = {	ID = 21,	CID = 302,	PetID = -1,	Content = [[有敌人靠近啦！主人，一旦他们走到最右侧，战斗就会失败，所以要在那之前把他们全部消灭！]],	Type = 0,	Sound = [[htp_battle_07.mp3]],},
	[22] = {	ID = 22,	CID = 19,	PetID = 0,	Content = [[嘿！嘿！刚才的故事是不是非常的精彩啊？]],	Type = 0,	Sound = [[htp_doc01.mp3]],},
	[23] = {	ID = 23,	CID = 20,	PetID = 0,	Content = [[你一定在想我刚才为什么没有把故事讲完，对吗？]],	Type = 0,	Sound = 0,},
	[24] = {	ID = 24,	CID = 21,	PetID = 0,	Content = [[可惜那一战的所有人，至今没有下落。]],	Type = 0,	Sound = [[htp_doc03.mp3]],},
	[25] = {	ID = 25,	CID = 22,	PetID = 0,	Content = [[呵呵，不说这个了，还没问你的名字呢。]],	Type = 0,	Sound = [[htp_doc04.mp3]],},
	[26] = {	ID = 26,	CID = 23,	PetID = 0,	Content = [[很高兴认识你。那么，作为见面礼，请选择一位伙伴吧！]],	Type = 0,	Sound = [[htp_doc05.mp3]],},
	[27] = {	ID = 27,	CID = 24,	PetID = 0,	Content = [[你选了她呀，这可是我最心爱的一个哟，一定要好好对她呀！再见啦！]],	Type = 0,	Sound = 0,},
	[28] = {	ID = 28,	CID = 25,	PetID = -1,	Content = [[亲爱的主人，很高兴能和你一起冒险！为了让我们的旅途更加精彩，让我们去召唤更多的小伙伴吧~！]],	Type = 0,	Sound = [[htp_begin01.mp3]],},
	[29] = {	ID = 29,	CID = 201,	PetID = -1,	Content = [[在这里，不同的城市能召唤不同的顶级精灵哦，而且每个城市都有各自的特色！]],	Type = 0,},
	[30] = {	ID = 30,	CID = 202,	PetID = -1,	Content = [[好了，让我们现在召唤第一个伙伴吧！]],	Type = 0,	Sound = [[htp_doc08.mp3]],},
	[31] = {	ID = 31,	CID = 26,	PetID = -1,	Content = [[哇~！有一位强大的伙伴加入我们了呢！让他和我们一起战斗吧！]],	Type = 0,	Sound = [[htp_begin02.mp3]],},
	[32] = {	ID = 32,	CID = 27,	PetID = -1,	Content = [[哈哈~，看起来我们的小队已经成型啦！出发喽！]],	Type = 0,	Sound = [[htp_begin03.mp3]],},
	[33] = {	ID = 33,	CID = 28,	PetID = -1,	Content = [[主人，触摸这个石碑，就可以知道我们的探索目标，快看看吧！]],	Type = 0,	Sound = [[htp_begin04.mp3]],},
	[34] = {	ID = 34,	CID = 29,	PetID = -1,	Content = [[让我们试着打开森林中的迷雾。]],	Type = 0,	Sound = [[htp_begin05.mp3]],},
	[35] = {	ID = 35,	CID = 30,	PetID = -1,	Content = [[噢耶！这里藏了一些金币呢！快点把这些可爱的金币收起来吧。]],	Type = 0,	Sound = 0,},
	[36] = {	ID = 36,	CID = 31,	PetID = -1,	Content = [[哈哈，找你好久啦！原来你躲在这里！主人，开始战斗吧。]],	Type = 0,	Sound = [[htp_begin07.mp3]],},
	[37] = {	ID = 37,	CID = 203,	PetID = -1,	Content = [[哈哈，我们抓住他了 ，现在他成为我们的伙伴了。]],	Type = 0,},
	[38] = {	ID = 38,	CID = 33,	PetID = -1,	Content = [[主人，还有一个精灵躲在这片区域，找到并击败他我们就可以去下个城镇啦~]],	Type = 0,	Sound = [[htp_begin08.mp3]],},
	[39] = {	ID = 39,	CID = 34,	PetID = -1,	Content = [[这些敌人弱爆了！主人看来不需要你动手啦，点击自动我们就能替你把敌人消灭。]],	Type = 0,	Sound = [[htp_begin09.mp3]],},
	[40] = {	ID = 40,	CID = 35,	PetID = -1,	Content = [[主人，我们成功的完成了任务呢！如果主人想要重新探索这里的话，重新进来一次就可以了哦。]],	Type = 0,	Sound = [[htp_begin10.mp3]],},
	[41] = {	ID = 41,	CID = 36,	PetID = -1,	Content = [[咦？刚才的敌人好像掉了一个东西在那里呢！快拿起来看看吧！]],	Type = 0,	Sound = 0,},
	[42] = {	ID = 42,	CID = 37,	PetID = -1,	Content = [[主人，我们看到你的包包里面好像有一把武器，把它送给我吧！好不好嘛~~好不好嘛~~！]],	Type = 0,	Sound = [[htp_begin12.mp3]],},
	[43] = {	ID = 43,	CID = 38,	PetID = -1,	Content = [[呵呵呵呵，我终于有武器了。这个武器应该还有升级空间，试着给他升级看看吧！]],	Type = 0,	Sound = [[htp_begin13.mp3]],},
	[44] = {	ID = 44,	CID = 39,	PetID = -1,	Content = [[我觉得我现在的战斗力已经爆表啦！我们去探索更神秘的区域吧！]],	Type = 0,	Sound = [[htp_begin14.mp3]],},
	[45] = {	ID = 45,	CID = 204,	PetID = -1,	Content = [[以主人的能力后面一定能进行独立探索了！嗯，我相信亲爱的主人一定行的！那么，这个礼包送给主人吧！]],	Type = 0,	Sound = [[htp_begin15.mp3]],},
	[46] = {	ID = 46,	CID = 301,	PetID = -1,	Content = [[主人，又有新的伙伴加入我们了呢，让他和我们一起战斗吧！]],	Type = 0,	Sound = [[htp_begin16.mp3]],},
	[47] = {	ID = 47,	CID = 40,	PetID = -1,	Content = [[金砖！这是金砖耶！哇哦~~！这个好稀有的！]],	Type = 0,	Sound = [[htp_begin_92.mp3]],},
	[48] = {	ID = 48,	CID = 41,	PetID = -1,	Content = [[主人如果你手指速度够快的话就可以拿到好多好多金币，点得越快拿的越多哦！主人赶紧试试吧！]],	Type = 0,	Sound = [[htp_begin_93.mp3]],},
	[49] = {	ID = 49,	CID = 205,	PetID = -1,	Content = [[哈哈，主人真棒，我们已经把这里全部探索过啦！终于可以去探索新的未知领域了呢！yeah~~]],	Type = 0,	Sound = [[htp_begin_94.mp3]],},
	[50] = {	ID = 50,	CID = 206,	PetID = -1,	Content = [[主人快看，刚才获得了一个安抚果实呢，精灵吃掉它的话就会获得经验然后升级哦。]],	Type = 0,	Sound = [[htp_begin_95.mp3]],},
	[51] = {	ID = 51,	CID = 207,	PetID = -1,	Content = [[快点吃掉它吧！]],	Type = 0,	Sound = [[htp_begin_96.mp3]],},
	[52] = {	ID = 52,	CID = 208,	PetID = -1,	Content = [[哇~~！升级啦，升级啦！触摸果实，它会引导你哪里可以获得更多果实哦！好啦，现在让我们继续前进吧！]],	Type = 0,	Sound = [[htp_begin_97.mp3]],},
	[53] = {	ID = 53,	CID = 42,	PetID = -1,	Content = [[主人我发现了这个！]],	Type = 0,	Sound = [[htp_unlock2-1.mp3]],},
	[54] = {	ID = 54,	CID = 43,	PetID = -1,	Content = [[没见过吧！说出来吓你一跳哦！]],	Type = 0,	Sound = [[htp_unlock2-2.mp3]],},
	[55] = {	ID = 55,	CID = 44,	PetID = -1,	Content = [[这可是觉醒石！它可以让我变得比现在还厉害哦！我已经准备好了，主人！让我们开始吧！]],	Type = 0,	Sound = [[htp_unlock2-3.mp3]],},
	[56] = {	ID = 56,	CID = 45,	PetID = -1,	Content = [[主人，不止可以觉醒一次的哦！觉醒到一定次数后还能解锁强大的被动技能，想想就有点小激动呢！]],	Type = 0,	Sound = [[htp_unlock2-4.mp3]],},
	[57] = {	ID = 57,	CID = 46,	PetID = -1,	Content = [[主人，有个新区域开放了哦。据说那里藏着很多装备，我们一起去寻宝吧！]],	Type = 0,	Sound = [[htp_unlock3-1.mp3]],},
	[58] = {	ID = 58,	CID = 47,	PetID = -1,	Content = [[不过可不要轻易的去挑战高难度哦，虽然可以拿到更好的东西，但是也会死的很惨~~~！！]],	Type = 0,	Sound = [[htp_unlock3-2.mp3]],},
	[59] = {	ID = 59,	CID = 48,	PetID = -1,	Content = [[主人，刚刚大木博士给我们寄过来了一些装备，包里的~装备~太多了，我~已经~背~背~~不动了~~。我们用~合成装置~把这些~破烂~变成更好的装备吧！]],	Type = 0,	Sound = [[htp_unlock4-1.mp3]],},
	[60] = {	ID = 60,	CID = 49,	PetID = -1,	Content = [[利用合成装置，我们可以把5个相同品质的装备变成品质更高的装备哦。]],	Type = 0,	Sound = [[htp_unlock4-2.mp3]],},
	[61] = {	ID = 61,	CID = 50,	PetID = -1,	Content = [[主人，听说黑市开张了呢。那里有什么精灵的碎片啦、什么觉醒石啦，反正很多好东西啦~。我们去逛逛吧！]],	Type = 0,	Sound = [[htp_unlock5-1.mp3]],},
	[62] = {	ID = 62,	CID = 51,	PetID = -1,	Content = [[呃~这个~这个，我们还是买它吧！哇，价格好划算呀！呃~~~！我忘了你的精灵之魂不够啊！好吧…跟我来…]],	Type = 0,	Sound = [[htp_unlock5-2.mp3]],},
	[63] = {	ID = 63,	CID = 52,	PetID = -1,	Content = [[精灵之魂可以通过献祭获得哦，现在我们开始吧。]],	Type = 0,	Sound = [[htp_unlock5-3.mp3]],},
	[64] = {	ID = 64,	CID = 53,	PetID = -1,	Content = [[现在我们有足够的精灵之魂,实力又可以提升啦！]],	Type = 0,	Sound = [[htp_unlock5-4.mp3]],},
	[65] = {	ID = 65,	CID = 209,	PetID = -1,	Content = [[主人，我推荐您可以去探索精英关卡，在这里可以获得非常厉害的五星精灵哦！]],	Type = 0,	Sound = [[htp_unlock5-5.mp3]],},
	[66] = {	ID = 66,	CID = 210,	PetID = -1,	Content = [[恭喜主人！现在让我们帮助小伙伴超越等级上限吧。]],	Type = 0,	Sound = [[htp_unlock5-6.mp3]],},
	[67] = {	ID = 67,	CID = 211,	PetID = -1,	Content = [[超越所需要的徽章只有精英关卡里面才有，我先送主人几个吧！]],	Type = 0,	Sound = [[htp_unlock5-7.mp3]],},
	[68] = {	ID = 68,	CID = 54,	PetID = -1,	Content = [[主人，这里就是万众瞩目的竞技场，有没有一点点紧张呢？]],	Type = 0,	Sound = [[htp_unlock7-1.mp3]],},
	[69] = {	ID = 69,	CID = 55,	PetID = -1,	Content = [[在竞技场中，我们可以挑战其他训练师，说不定还能交到朋友呢！]],	Type = 0,	Sound = [[htp_unlock7-2.mp3]],},
	[70] = {	ID = 70,	CID = 56,	PetID = -1,	Content = [[不过要注意的是，竞技场的战斗主人是没有办法干涉的哦，只能靠我们自己！]],	Type = 0,	Sound = [[htp_unlock7-3.mp3]],},
	[71] = {	ID = 71,	CID = 57,	PetID = -1,	Content = [[提醒一下主人，竞技场每天(晚上)9点都会根据排名发放荣誉奖励，荣誉可以兑换各种奖励，到时候别忘咯~！]],	Type = 0,	Sound = [[htp_unlock7-4.mp3]],},
	[72] = {	ID = 72,	CID = 58,	PetID = -1,	Content = [[主人，现在可以配置多个队伍了哦，而且随时切换，非常方便呢。]],	Type = 0,	Sound = [[htp_unlock7-5.mp3]],},
	[73] = {	ID = 73,	CID = 59,	PetID = -1,	Content = [[主人，训练中心开张了呢，在那里即使是你不在的时候，我们也可以获得大量经验哦！]],	Type = 0,	Sound = 0,},
	[74] = {	ID = 74,	CID = 60,	PetID = -1,	Content = [[而且在这里训练的同时，也不会妨碍在战斗的上阵呢！]],	Type = 0,	Sound = 0,},
	[75] = {	ID = 75,	CID = 61,	PetID = -1,	Content = [[这里的训练模式看起来十分丰富，使用精灵石可以有几率进入新的训练模式哦。]],	Type = 0,	Sound = 0,},
	[76] = {	ID = 76,	CID = 62,	PetID = -1,	Content = [[因为这里正在开业特惠，我们可以免费使用一次最有效的地狱模式，快试试吧！]],	Type = 0,	Sound = 0,},
	[77] = {	ID = 77,	CID = 63,	PetID = -1,	Content = [[主人，训练一次是8小时，到时可要记得回来把我们带走哦，这样才能领取经验！]],	Type = 0,	Sound = 0,},
	[78] = {	ID = 78,	CID = 64,	PetID = -1,	Content = [[不过，使用精灵石可以提前结束训练，而且可以获得全部8小时的经验。哇~~开业特惠不要钱~，主人我们快结束训练吧！]],	Type = 0,	Sound = 0,},
	[79] = {	ID = 79,	CID = 303,	PetID = -1,	Content = [[主人，“突破”可以提升装备的等级上限！]],	Type = 0,	Sound = [[htp_unlock8-0.mp3]],},
	[80] = {	ID = 80,	CID = 65,	PetID = -1,	Content = [[主人~给人家的装备突破一下嘛~~。突破一下嘛~~！Yeah！主人最好啦~！]],	Type = 0,	Sound = [[htp_unlock8-1.mp3]],},
	[81] = {	ID = 81,	CID = 66,	PetID = -1,	Content = [[主人，传说有一座冠军之塔，只要战胜塔中的守卫就可以获得丰厚的奖励！]],	Type = 0,	Sound = [[htp_unlock8-2.mp3]],},
	[82] = {	ID = 82,	CID = 67,	PetID = -1,	Content = [[主人，在冠军之塔里，每场战斗后我们是不会恢复体力的，只有重置后才会恢复，所以在战斗中尽量控制血量！精灵死亡时，可以换一只健康的精灵上阵！（10级以上）]],	Type = 0,	Sound = [[htp_unlock8-3.mp3]],},
	[83] = {	ID = 83,	CID = 68,	PetID = -1,	Content = [[主人，之前获得的冠军徽章可以在这里兑换BUFF来增强实力哦。不过增强的效果只会在冠军之塔中起作用！]],	Type = 0,	Sound = [[htp_unlock8-4.mp3]],},
	[84] = {	ID = 84,	CID = 69,	PetID = -1,	Content = [[主人！你终于回来了！想死你啦！大木博士给你指定了详细的长期成长计划！每天都不一样呢，别忘了看看呀。]],	Type = 0,	Sound = [[htp_unlock9-1.mp3]],},
	[85] = {	ID = 85,	CID = 70,	PetID = -1,	Content = [[主人！是神兽！我们刚才看到了神兽！！神兽身上携带着非常珍贵的物品，而且如果能让神兽加入我们的话~哦~天哪！我知道他往哪里跑了，快跟我来！]],	Type = 0,	Sound = [[htp_unlock9-2.mp3]],},
	[86] = {	ID = 86,	CID = 71,	PetID = -1,	Content = [[主人，我感到体内一股强大的能量正要迸发出来，激发我无穷的潜力吧！]],	Type = 0,	Sound = [[htp_unlock9-3.mp3]],},
	[87] = {	ID = 87,	CID = 72,	PetID = -1,	Content = [[精灵们把这个过程叫做“潜力激发”。激发会消耗掉相应的潜力点。]],	Type = 0,	Sound = [[htp_unlock9-4.mp3]],},
	[88] = {	ID = 88,	CID = 212,	PetID = -1,	Content = [[潜力点十分珍贵哦，每升一级才获得一点哦，如果失败就白白浪费啦！]],	Type = 0,	Sound = [[htp_unlock9-5.mp3]],},
	[89] = {	ID = 89,	CID = 213,	PetID = -1,	Content = [[啊~~！主人，请稍等一下！我刚才在路边捡到了2颗精灵石，运气真好呢，送给主人吧！而且，用精灵石进行激发一定会成功的哦！]],	Type = 0,	Sound = [[htp_unlock9-6.mp3]],},
	[90] = {	ID = 90,	CID = 73,	PetID = -1,	Content = [[主人，你看起来又变强了呢！我知道有个地方，那里藏了很多很多金币哦！快跟我来吧！]],	Type = 0,	Sound = [[htp_unlock9-7.mp3]],},
	[91] = {	ID = 91,	CID = 74,	PetID = -1,	Content = [[主人，小伙伴们可以进行重生了呢！快去看看吧~。]],	Type = 0,	Sound = [[htp_unlock9-8.mp3]],},
	[92] = {	ID = 92,	CID = 214,	PetID = -1,	Content = [[重生会使精灵恢复到初始状态，但能获得之前觉醒和升级时所消耗的全部材料和道具。会不会有点小激动呢。]],	Type = 0,	Sound = [[htp_unlock9-9.mp3]],},
	[93] = {	ID = 93,	CID = 75,	PetID = -1,	Content = [[主人，你知道吗？装备通过重铸水晶重铸之后将会更加的厉害哦！我刚刚收集到了一些水晶，都送给主人吧！]],	Type = 0,	Sound = [[htp_unlock9-10.mp3]],},
	[94] = {	ID = 94,	CID = 215,	PetID = -1,	Content = [[重铸可以提升装备的成长值，让它更加强力！主人，让我们来尝试一下吧。]],	Type = 0,	Sound = [[htp_unlock9-11.mp3]],},
	[95] = {	ID = 95,	CID = 76,	PetID = -1,	Content = [[主人，我们的装备可以进行回炉啦，快去看看吧~]],	Type = 0,	Sound = [[htp_unlock10-1.mp3]],},
	[96] = {	ID = 96,	CID = 304,	PetID = -1,	Content = [[主人，将不再需要的装备回炉，可以获得之前消耗的所有突破材料、绝大部分金币和重铸水晶。]],	Type = 0,	Sound = [[htp_unlock10-2.mp3]],},
	[97] = {	ID = 97,	CID = 77,	PetID = -1,	Content = [[主人，以我们的实力可以去参加馆长争夺战啦，快去报名吧！]],	Type = 0,	Sound = 0,},
	[98] = {	ID = 98,	CID = 78,	PetID = -1,	Content = [[报告主人，我在草丛里发现了一颗宝石！]],	Type = 0,	Sound = [[htp_unlock11-1.mp3]],},
	[99] = {	ID = 99,	CID = 79,	PetID = -1,	Content = [[可以消耗其他宝石来提升主宝石的等级。]],	Type = 0,	Sound = [[htp_unlock11-2.mp3]],},
	[100] = {	ID = 100,	CID = 80,	PetID = -1,	Content = [[高级的宝石升级有可能会失败，消耗的宝石等级越高，升级成功率越高。]],	Type = 0,	Sound = [[htp_unlock11-3.mp3]],},
	[101] = {	ID = 101,	CID = 81,	PetID = -1,	Content = [[装备这颗强力宝石之后，我们的实力又可以提升啦]],	Type = 0,	Sound = [[htp_unlock11-4.mp3]],},
	[102] = {	ID = 102,	CID = 82,	PetID = -1,	Content = [[主人，通过进化，可以变成高阶形态，提升大量属性和技能等级！]],	Type = 0,	Sound = [[htp_unlock12-1.mp3]],},
	[103] = {	ID = 103,	CID = 83,	PetID = -1,	Content = [[主人，进化需要精灵等级和进化石。进化石可以在黑市和活动副本里获得哦~主人，快努力让我进化吧！]],	Type = 0,	Sound = [[htp_unlock12-2.mp3]],},
	[104] = {	ID = 104,	CID = 84,	PetID = -1,	Content = [[主人，传说装备中心会出现超厉害的武器呢，咱们去试试运气吧。]],	Type = 0,	Sound = [[htp_unlock14_01.mp3]],},
	[105] = {	ID = 105,	CID = 85,	PetID = -1,	Content = [[哇，人品爆发啦，貌似很好的装备耶。]],	Type = 0,	Sound = [[htp_unlock14_02.mp3]],},
	[106] = {	ID = 106,	CID = 86,	PetID = -1,	Content = [[主人，我看你好像有点疲劳的样子呢。那我告诉主人一个小秘密吧！那就是“扫荡”！]],	Type = 0,	Sound = [[htp_unlock16_01.mp3]],},
	[107] = {	ID = 107,	CID = 87,	PetID = -1,	Content = [[在主人发布扫荡命令后，我们会帮主人快速的在关卡中搜索各种道具和进化石哦，这样一举两得的事情是不是很棒呀~！]],	Type = 0,	Sound = [[htp_unlock16_02.mp3]],},
	[108] = {	ID = 108,	CID = 88,	PetID = -1,	Content = [[主人,你应该还有一个地方没有去过吧！跟我来吧！]],	Type = 0,	Sound = [[htp_unlock18_01.mp3]],},
	[109] = {	ID = 109,	CID = 89,	PetID = -1,	Content = [[在这里主人可以通过充值购买精灵石，同时获得各种VIP特权哦。现在我们来看看VIP有哪些特权吧！]],	Type = 0,	Sound = [[htp_unlock18_02.mp3]],},
	[110] = {	ID = 110,	CID = 90,	PetID = -1,	Content = [[别忘了还有VIP礼包可以领取哦！]],	Type = 0,	Sound = [[htp_unlock18_03.mp3]],},
	[111] = {	ID = 111,	CID = 91,	PetID = -1,	Content = [[您现在可以探索英雄副本啦！在这里，可以获得精灵120级以后升级所需的材料哦！]],	Type = 0,	Sound = 0,},
}

return _table
