--[[
	id = id
question = 问题
answerdata = 答案选项
answer = 答案(0错误,1正确）

--]]
local _table = {
	[1] = {	id = 1,	question = [[挖掘机技术哪家强，中国山东找蓝翔。这句话是否正确？]],	answerdata = {'正确','错误'},	answer = 1,},
	[2] = {	id = 2,	question = [[被烟火围困，暂时无法逃离时应尽量呆在哪里？]],	answerdata = {'床上','阁楼上','窗口','门边'},	answer = 3,},
	[3] = {	id = 3,	question = [[鲤鱼王可以进化成什么精灵？]],	answerdata = {'鲤鱼龙','独角金鱼','金鱼王','暴鲤龙'},	answer = 4,},
	[4] = {	id = 4,	question = [[水晶版中,杰尼龟撒水壶有什么作用？]],	answerdata = {'吸引精灵','灭火','唤醒胡说树','装饰品'},	answer = 3,},
	[5] = {	id = 5,	question = [[火焰鸡不可以学会什么技能？]],	answerdata = {'水枪','火焰踢','居合斩','火焰拳击'},	answer = 1,},
	[6] = {	id = 6,	question = [[能使精灵的毒系技能威力提升的是？]],	answerdata = {'毒针','尖锐鸟嘴','神秘水滴','黑色眼镜'},	answer = 1,},
	[7] = {	id = 7,	question = [[白金版本中,道具'青空石板'能提升什么系的威力？]],	answerdata = {'飞行系','火系','龙系','鬼系'},	answer = 1,},
	[8] = {	id = 8,	question = [[口袋妖怪中,哪个版本首次加入了2V2系统？]],	answerdata = {'金银版','珍珠钻石','火红叶绿','红蓝宝石'},	answer = 4,},
	[9] = {	id = 9,	question = [[在银版中,共有多少种秘传机？]],	answerdata = {'1种','4种','7种','12种'},	answer = 3,},
	[10] = {	id = 10,	question = [[烧焦塔和什么塔是一对？]],	answerdata = {'冠军之塔','喇叭芽塔','钟之塔','玲玲塔'},	answer = 4,},
	[11] = {	id = 11,	question = [[黄版中,浅红市的原野森林捕猎区每次最多走多少步？]],	answerdata = {'3000步','100步','500步','无限'},	answer = 3,},
	[12] = {	id = 12,	question = [[金版中,在自然公园进行比赛的第一名能获得的道具是？]],	answerdata = {'太阳石','树果','奖杯','自行车'},	answer = 1,},
	[13] = {	id = 13,	question = [[黄版中,成为联盟冠军后,可以去浅蓝市郊外洞穴捕捉什么精灵？]],	answerdata = {'梦幻','伊布','超梦','快龙'},	answer = 3,},
	[14] = {	id = 14,	question = [[红蓝宝石版中,第8个道馆是什么系道馆？]],	answerdata = {'电系','岩石系','水系','火系'},	answer = 3,},
	[15] = {	id = 15,	question = [[在玉虫市与忠于职守但口渴的门卫对话后,主角送了门卫什么？]],	answerdata = {'王老吉','维他奶','维他爷','茶'},	answer = 4,},
	[16] = {	id = 16,	question = [[获得什么技能可以自由飞越去过的城市？]],	answerdata = {'飞空术','居合斩','潜水术','冲浪术'},	answer = 1,},
	[17] = {	id = 17,	question = [[红宝石中,谁把居合斩送给主角？]],	answerdata = {'老师','船长','医生','东尼大木'},	answer = 2,},
	[18] = {	id = 18,	question = [[红宝石中天空之柱的顶层有什么？]],	answerdata = {'霸道总裁','裂空座','QQ企鹅','蓝猫'},	answer = 2,},
	[19] = {	id = 19,	question = [[红宝石里的熔岩神兽是？]],	answerdata = {'超梦','海皇牙','古拉顿','梦幻'},	answer = 3,},
	[20] = {	id = 20,	question = [[红蓝宝石版中,四大天王中的第一个是什么系的精灵？]],	answerdata = {'冰系','幽灵系','恶系','龙系'},	answer = 3,},
	[21] = {	id = 21,	question = [[进化一次后的妙蛙种子叫什么名字？]],	answerdata = {'妙蛙草','妙蛙花','妙蛙仙人','蛤蟆文太'},	answer = 1,},
	[22] = {	id = 22,	question = [[黄版中,月见山前的精灵中心有一人以500元卖出什么精灵？]],	answerdata = {'鲤鱼王','绿毛虫','皮皮','卡斯'},	answer = 1,},
	[23] = {	id = 23,	question = [[金版中,共有几个徽章？]],	answerdata = {'3个','11个','5个','8个'},	answer = 4,},
	[24] = {	id = 24,	question = [[超梦来袭在每天的21:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 1,},
	[25] = {	id = 25,	question = [[超梦来袭在每天的0:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[26] = {	id = 26,	question = [[超梦来袭在每天的1:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[27] = {	id = 27,	question = [[超梦来袭在每天的2:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[28] = {	id = 28,	question = [[超梦来袭在每天的3:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[29] = {	id = 29,	question = [[超梦来袭在每天的4:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[30] = {	id = 30,	question = [[超梦来袭在每天的5:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[31] = {	id = 31,	question = [[超梦来袭在每天的6:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[32] = {	id = 32,	question = [[超梦来袭在每天的20:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[33] = {	id = 33,	question = [[超梦来袭在每天的22:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[34] = {	id = 34,	question = [[超梦来袭在每天的23:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[35] = {	id = 35,	question = [[闪电鸟来袭在每天的21:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[36] = {	id = 36,	question = [[闪电鸟来袭在每天的0:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[37] = {	id = 37,	question = [[闪电鸟来袭在每天的1:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[38] = {	id = 38,	question = [[闪电鸟来袭在每天的2:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[39] = {	id = 39,	question = [[闪电鸟来袭在每天的9:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[40] = {	id = 40,	question = [[闪电鸟来袭在每天的10:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[41] = {	id = 41,	question = [[闪电鸟来袭在每天的11:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[42] = {	id = 42,	question = [[闪电鸟来袭在每天的12:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 1,},
	[43] = {	id = 43,	question = [[闪电鸟来袭在每天的13:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[44] = {	id = 44,	question = [[闪电鸟来袭在每天的14:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[45] = {	id = 45,	question = [[闪电鸟来袭在每天的15:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[46] = {	id = 46,	question = [[闪电鸟来袭在每天的16:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[47] = {	id = 47,	question = [[闪电鸟来袭在每天的17:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[48] = {	id = 48,	question = [[闪电鸟来袭在每天的23:00开启,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[49] = {	id = 49,	question = [[关卡中的金砖在点出后1秒会消失,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[50] = {	id = 50,	question = [[关卡中的金砖在点出后2秒会消失,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[51] = {	id = 51,	question = [[关卡中的金砖在点出后3秒会消失,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[52] = {	id = 52,	question = [[关卡中的金砖在点出后4秒会消失,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[53] = {	id = 53,	question = [[关卡中的金砖在点出后5秒会消失,对吗?]],	answerdata = {'正确','错误'},	answer = 1,},
	[54] = {	id = 54,	question = [[关卡中的金砖在点出后6秒会消失,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[55] = {	id = 55,	question = [[每天的11~13点和17~19点都可以吃香烤大葱鸭补充体力,对吗?]],	answerdata = {'正确','错误'},	answer = 1,},
	[56] = {	id = 56,	question = [[每天的1~3点和7~9点都可以吃香烤大葱鸭补充体力,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[57] = {	id = 57,	question = [[每天的2~3点和6~9点都可以吃香烤大葱鸭补充体力,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[58] = {	id = 58,	question = [[每天的2~4点和5~10点都可以吃香烤大葱鸭补充体力,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[59] = {	id = 59,	question = [[每天的3~5点和6~10点都可以吃香烤大葱鸭补充体力,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[60] = {	id = 60,	question = [[每天的7~8点和9~10点都可以吃香烤大葱鸭补充体力,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[61] = {	id = 61,	question = [[每天的8~9点和17~19点都可以吃香烤大葱鸭补充体力,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[62] = {	id = 62,	question = [[每天的10~11点和17~19点都可以吃香烤大葱鸭补充体力,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[63] = {	id = 63,	question = [[每天的11~13点和19~20点都可以吃香烤大葱鸭补充体力,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[64] = {	id = 64,	question = [[每天的14~15点和17~19点都可以吃香烤大葱鸭补充体力,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[65] = {	id = 65,	question = [[每天的11~13点和19~21点都可以吃香烤大葱鸭补充体力,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[66] = {	id = 66,	question = [[每天的11~13点和22~23点都可以吃香烤大葱鸭补充体力,对吗?]],	answerdata = {'正确','错误'},	answer = 2,},
	[67] = {	id = 67,	question = [[下列哪样东西在黑市中无法兑换得到的?]],	answerdata = {'觉醒之石','精灵碎片','宝石','装备'},	answer = 3,},
	[68] = {	id = 68,	question = [[为了救爱妾而引清兵入关的明末将领为:]],	answerdata = {'吴一桂','吴二桂','吴三桂','吴四桂'},	answer = 3,},
	[69] = {	id = 69,	question = [[原为唐高宗之后，后登基为帝，为中国第一个女皇帝的是：]],	answerdata = {'文则天','武则天','文则地','武则地'},	answer = 2,},
	[70] = {	id = 70,	question = [[东汉末年，刘备、关羽与何人互有盟约，约为兄弟：]],	answerdata = {'岳飞','张菲','王菲','张飞'},	answer = 4,},
	[71] = {	id = 71,	question = [[龙在十二生肖中排第几?]],	answerdata = {'第五','第六','第九','第十'},	answer = 1,},
	[72] = {	id = 72,	question = [[哈雷彗星绕太阳运行的周期约为多少年?]],	answerdata = {'73年','74年','75年','76年'},	answer = 4,},
	[73] = {	id = 73,	question = [[在'夸父逐日'中,'夸父'是怎样追逐太阳的?]],	answerdata = {'开车','骑马','奔跑','传送'},	answer = 3,},
	[74] = {	id = 74,	question = [[屈原是春秋时代哪国人?]],	answerdata = {'吴国','楚国','越国','齐国'},	answer = 2,},
	[75] = {	id = 75,	question = [[味精的主要成分是什么?]],	answerdata = {'谷氨二酸钠','谷氨酸钠','甲基谷氨酸钠','氯化钠'},	answer = 2,},
	[76] = {	id = 76,	question = [[企鹅一般在几月份产卵?]],	answerdata = {'5月','12月','9月','2月'},	answer = 1,},
	[77] = {	id = 77,	question = [['自由女神像'是哪个国家送给美国的礼物?]],	answerdata = {'英国','前苏联','法国','德国'},	answer = 3,},
	[78] = {	id = 78,	question = [[安徒生童话《海的女儿》里，小美人鱼变成人是为了见到谁?]],	answerdata = {'渔夫','皇后','王子','白雪公主'},	answer = 3,},
	[79] = {	id = 79,	question = [[最早、最完备的文字是什么文字?]],	answerdata = {'甲骨文','乙骨文','丙骨文','丁骨文'},	answer = 1,},
	[80] = {	id = 80,	question = [['春秋五霸'中,谁最先称霸?]],	answerdata = {'姜太公','洪七公','济公','齐桓公'},	answer = 4,},
	[81] = {	id = 81,	question = [[世界上最早的天文学著作是:]],	answerdata = {'月亮之上','星星知我心','昨夜星辰','甘石星经'},	answer = 4,},
	[82] = {	id = 82,	question = [[建立我国历史上第一个大一统帝国的人是：]],	answerdata = {'秦桧','秦香莲','秦琼','秦始皇'},	answer = 4,},
	[83] = {	id = 83,	question = [[皮卡丘会进化成如下哪只精灵？]],	answerdata = {'雷丘','皮皮','丘比特','丘处机'},	answer = 1,},
	[84] = {	id = 84,	question = [[雷丘会进化成如下哪只精灵？]],	answerdata = {'电击魔兽','暴龙兽','雷帝','无法进化'},	answer = 4,},
	[85] = {	id = 85,	question = [[绿毛虫会进化成如下哪只精灵？]],	answerdata = {'铁壳昆','铁甲蛹','裂空座','红毛丹'},	answer = 2,},
	[86] = {	id = 86,	question = [[波波会进化成如下哪只精灵？]],	answerdata = {'波可比','这波不亏','比比鸟','波塞冬'},	answer = 3,},
	[87] = {	id = 87,	question = [[小锯鳄会进化成如下哪只精灵？]],	answerdata = {'大嘴鳄','蓝鳄','大钳鳄','蓝鱼咢'},	answer = 2,},
	[88] = {	id = 88,	question = [[小火龙会进化成如下哪只精灵？]],	answerdata = {'小水蛇','火恐龙','暴龙兽','白龙马'},	answer = 2,},
	[89] = {	id = 89,	question = [[伊布不能进化成如下哪只精灵？]],	answerdata = {'火精灵','水精灵','叶精灵','蓝精灵'},	answer = 4,},
	[90] = {	id = 90,	question = [[炎帝、雷皇和水君是被哪只精灵复活的？]],	answerdata = {'凤王','火鸡','洛奇亚','火焰鸟'},	answer = 1,},
	[91] = {	id = 91,	question = [[被称为海神的是？]],	answerdata = {'水君','洛奇亚','诺基亚','急冻鸟'},	answer = 2,},
	[92] = {	id = 92,	question = [[神兽降临里可以遇到哪只神兽？]],	answerdata = {'火精灵','水君','雷母','炎公'},	answer = 2,},
	[93] = {	id = 93,	question = [[伊布在游戏中有几种进化形态？]],	answerdata = {'4','3','6','8'},	answer = 4,},
	[94] = {	id = 94,	question = [[封测时,曾被吐槽这他喵的不是男孩么怎么进化后成女孩了是哪只精灵？]],	answerdata = {'杰尼龟','皮卡丘','小火龙','走路草'},	answer = 1,},
	[95] = {	id = 230,	question = [[以下哪些精灵是在游戏中有出现的:]],	answerdata = {'皮卡丘','迪迦奥特曼','哥斯拉','乔布斯'},	answer = 1,},
}

return _table
