local Config = require "Config"

local FightGuider = class(LuaController)

function FightGuider:createDocument()
    self._factory:setZipFilePath(Config.COCOS_ZIP_DIR.."FightGuider.cocos.zip")
    return self._factory:createDocument("FightGuider.cocos")
end

--@@@@[[[[
function FightGuider:onInitXML()
	local set = self._set
    self._bg = set:getElfNode("bg")
    self._shader = set:getElfNode("shader")
    self._shader_rect = set:getRectangleNode("shader_rect")
    self._tips = set:getElfNode("tips")
    self._tips_portrait = set:getElfNode("tips_portrait")
    self._tips_portrait_pic = set:getElfNode("tips_portrait_pic")
    self._tips_bg2 = set:getElfNode("tips_bg2")
    self._tips_bg = set:getElfNode("tips_bg")
    self._tips_bg_name = set:getLabelNode("tips_bg_name")
    self._tips_bg_info = set:getLabelNode("tips_bg_info")
    self._graph = set:getElfNode("graph")
    self._graph_bg = set:getElfNode("graph_bg")
    self._graph_career1 = set:getElfGrayNode("graph_career1")
    self._graph_career2 = set:getElfGrayNode("graph_career2")
    self._graph_career3 = set:getElfGrayNode("graph_career3")
    self._graph_career4 = set:getElfGrayNode("graph_career4")
    self._graph_label = set:getLabelNode("graph_label")
    self._graph_line1_2 = set:getElfNode("graph_line1_2")
    self._graph_line2_3 = set:getElfNode("graph_line2_3")
    self._graph_line3_1 = set:getElfNode("graph_line3_1")
    self._graph_line1_2Gray = set:getElfNode("graph_line1_2Gray")
    self._graph_line2_3Gray = set:getElfNode("graph_line2_3Gray")
    self._graph_line3_1Gray = set:getElfNode("graph_line3_1Gray")
    self._touchBtn = set:getButtonNode("touchBtn")
    self._shader = set:getElfNode("shader")
    self._shader_sb_circle = set:getElfNode("shader_sb_circle")
    self._shader_rect = set:getRectangleNode("shader_rect")
    self._effect = set:getElfNode("effect")
    self._effect_YD_zhezhao1 = set:getElfNode("effect_YD_zhezhao1")
    self._effect_YD_zhezhao2 = set:getElfNode("effect_YD_zhezhao2")
    self._effect_YD_zhezhao3 = set:getElfNode("effect_YD_zhezhao3")
    self._effect_YD_jiantou = set:getElfNode("effect_YD_jiantou")
    self._effect_button = set:getButtonNode("effect_button")
    self._shader = set:getElfNode("shader")
    self._shader_sb_circle = set:getElfNode("shader_sb_circle")
    self._shader_rect = set:getRectangleNode("shader_rect")
    self._effect = set:getElfNode("effect")
    self._effect_YD_zhezhao1 = set:getElfNode("effect_YD_zhezhao1")
    self._effect_YD_zhezhao2 = set:getElfNode("effect_YD_zhezhao2")
    self._effect_YD_zhezhao3 = set:getElfNode("effect_YD_zhezhao3")
    self._effect_YD_jiantou = set:getElfNode("effect_YD_jiantou")
    self._effect_button = set:getButtonNode("effect_button")
    self._shader = set:getElfNode("shader")
    self._shader_rect = set:getRectangleNode("shader_rect")
    self._tips = set:getElfNode("tips")
    self._tips_portrait = set:getElfNode("tips_portrait")
    self._tips_portrait_pic = set:getElfNode("tips_portrait_pic")
    self._tips_bg2 = set:getElfNode("tips_bg2")
    self._tips_bg = set:getElfNode("tips_bg")
    self._tips_bg_name = set:getLabelNode("tips_bg_name")
    self._tips_bg_info = set:getLabelNode("tips_bg_info")
    self._graph = set:getElfNode("graph")
    self._graph_bg = set:getElfNode("graph_bg")
    self._graph_career1 = set:getElfGrayNode("graph_career1")
    self._graph_career2 = set:getElfGrayNode("graph_career2")
    self._graph_career3 = set:getElfGrayNode("graph_career3")
    self._graph_career4 = set:getElfGrayNode("graph_career4")
    self._graph_label = set:getLabelNode("graph_label")
    self._graph_line1_2 = set:getElfNode("graph_line1_2")
    self._graph_line2_3 = set:getElfNode("graph_line2_3")
    self._graph_line3_1 = set:getElfNode("graph_line3_1")
    self._graph_line1_2Gray = set:getElfNode("graph_line1_2Gray")
    self._graph_line2_3Gray = set:getElfNode("graph_line2_3Gray")
    self._graph_line3_1Gray = set:getElfNode("graph_line3_1Gray")
    self._touchBtn = set:getButtonNode("touchBtn")
    self._shader = set:getElfNode("shader")
    self._shader_sb_circle = set:getElfNode("shader_sb_circle")
    self._shader_rect = set:getRectangleNode("shader_rect")
    self._effect = set:getElfNode("effect")
    self._effect_YD_zhezhao1 = set:getElfNode("effect_YD_zhezhao1")
    self._effect_YD_zhezhao2 = set:getElfNode("effect_YD_zhezhao2")
    self._effect_YD_zhezhao3 = set:getElfNode("effect_YD_zhezhao3")
    self._effect_YD_jiantou = set:getElfNode("effect_YD_jiantou")
    self._effect_button = set:getButtonNode("effect_button")
    self._shader = set:getElfNode("shader")
    self._shader_sb_circle = set:getElfNode("shader_sb_circle")
    self._shader_rect = set:getRectangleNode("shader_rect")
    self._effect = set:getElfNode("effect")
    self._effect_YD_zhezhao1 = set:getElfNode("effect_YD_zhezhao1")
    self._effect_YD_zhezhao2 = set:getElfNode("effect_YD_zhezhao2")
    self._effect_YD_zhezhao3 = set:getElfNode("effect_YD_zhezhao3")
    self._effect_YD_jiantou = set:getElfNode("effect_YD_jiantou")
    self._effect_button = set:getButtonNode("effect_button")
    self._shader = set:getElfNode("shader")
    self._shader_rect = set:getRectangleNode("shader_rect")
    self._tips = set:getElfNode("tips")
    self._tips_portrait = set:getElfNode("tips_portrait")
    self._tips_portrait_pic = set:getElfNode("tips_portrait_pic")
    self._tips_bg2 = set:getElfNode("tips_bg2")
    self._tips_bg = set:getElfNode("tips_bg")
    self._tips_bg_name = set:getLabelNode("tips_bg_name")
    self._tips_bg_info = set:getLabelNode("tips_bg_info")
    self._graph = set:getElfNode("graph")
    self._graph_bg = set:getElfNode("graph_bg")
    self._graph_career1 = set:getElfGrayNode("graph_career1")
    self._graph_career2 = set:getElfGrayNode("graph_career2")
    self._graph_career3 = set:getElfGrayNode("graph_career3")
    self._graph_career4 = set:getElfGrayNode("graph_career4")
    self._graph_label = set:getLabelNode("graph_label")
    self._graph_line1_2 = set:getElfNode("graph_line1_2")
    self._graph_line2_3 = set:getElfNode("graph_line2_3")
    self._graph_line3_1 = set:getElfNode("graph_line3_1")
    self._graph_line1_2Gray = set:getElfNode("graph_line1_2Gray")
    self._graph_line2_3Gray = set:getElfNode("graph_line2_3Gray")
    self._graph_line3_1Gray = set:getElfNode("graph_line3_1Gray")
    self._touchBtn = set:getButtonNode("touchBtn")
    self._shader = set:getElfNode("shader")
    self._shader_sb_circle = set:getElfNode("shader_sb_circle")
    self._shader_rect = set:getRectangleNode("shader_rect")
    self._effect = set:getElfNode("effect")
    self._effect_YD_zhezhao1 = set:getElfNode("effect_YD_zhezhao1")
    self._effect_YD_zhezhao2 = set:getElfNode("effect_YD_zhezhao2")
    self._effect_YD_zhezhao3 = set:getElfNode("effect_YD_zhezhao3")
    self._effect_YD_jiantou = set:getElfNode("effect_YD_jiantou")
    self._effect_button = set:getButtonNode("effect_button")
    self._shader = set:getElfNode("shader")
    self._shader_sb_circle = set:getElfNode("shader_sb_circle")
    self._shader_rect = set:getRectangleNode("shader_rect")
    self._effect = set:getElfNode("effect")
    self._effect_YD_zhezhao1 = set:getElfNode("effect_YD_zhezhao1")
    self._effect_YD_zhezhao2 = set:getElfNode("effect_YD_zhezhao2")
    self._effect_YD_zhezhao3 = set:getElfNode("effect_YD_zhezhao3")
    self._effect_YD_jiantou = set:getElfNode("effect_YD_jiantou")
    self._effect_button = set:getButtonNode("effect_button")
    self._shader = set:getElfNode("shader")
    self._shader_rect = set:getRectangleNode("shader_rect")
    self._tips = set:getElfNode("tips")
    self._tips_portrait = set:getElfNode("tips_portrait")
    self._tips_portrait_pic = set:getElfNode("tips_portrait_pic")
    self._tips_bg2 = set:getElfNode("tips_bg2")
    self._tips_bg = set:getElfNode("tips_bg")
    self._tips_bg_name = set:getLabelNode("tips_bg_name")
    self._tips_bg_info = set:getLabelNode("tips_bg_info")
    self._tips_bg_button = set:getButtonNode("tips_bg_button")
    self._touchBtn = set:getButtonNode("touchBtn")
    self._shader = set:getElfNode("shader")
    self._shader_sb_circle = set:getElfNode("shader_sb_circle")
    self._shader_rect = set:getRectangleNode("shader_rect")
    self._effect = set:getElfNode("effect")
    self._effect_YD_zhezhao1 = set:getElfNode("effect_YD_zhezhao1")
    self._effect_YD_zhezhao2 = set:getElfNode("effect_YD_zhezhao2")
    self._effect_YD_zhezhao3 = set:getElfNode("effect_YD_zhezhao3")
    self._effect_YD_jiantou = set:getElfNode("effect_YD_jiantou")
    self._effect_button = set:getButtonNode("effect_button")
    self._shader = set:getElfNode("shader")
    self._shader_sb_circle = set:getElfNode("shader_sb_circle")
    self._shader_rect = set:getRectangleNode("shader_rect")
    self._effect = set:getElfNode("effect")
    self._effect_YD_zhezhao1 = set:getElfNode("effect_YD_zhezhao1")
    self._effect_YD_zhezhao2 = set:getElfNode("effect_YD_zhezhao2")
    self._effect_YD_zhezhao3 = set:getElfNode("effect_YD_zhezhao3")
    self._effect_YD_jiantou = set:getElfNode("effect_YD_jiantou")
    self._effect_button = set:getButtonNode("effect_button")
    self._shader = set:getElfNode("shader")
    self._shader_sb_circle = set:getElfNode("shader_sb_circle")
    self._shader_rect = set:getRectangleNode("shader_rect")
    self._effect = set:getElfNode("effect")
    self._effect_YD_zhezhao1 = set:getElfNode("effect_YD_zhezhao1")
    self._effect_YD_zhezhao2 = set:getElfNode("effect_YD_zhezhao2")
    self._effect_YD_zhezhao3 = set:getElfNode("effect_YD_zhezhao3")
    self._effect_YD_jiantou = set:getElfNode("effect_YD_jiantou")
    self._effect_button = set:getButtonNode("effect_button")
    self._shader = set:getElfNode("shader")
    self._shader_sb_circle = set:getElfNode("shader_sb_circle")
    self._shader_rect = set:getRectangleNode("shader_rect")
    self._effect = set:getElfNode("effect")
    self._effect_YD_zhezhao1 = set:getElfNode("effect_YD_zhezhao1")
    self._effect_YD_zhezhao2 = set:getElfNode("effect_YD_zhezhao2")
    self._effect_YD_zhezhao3 = set:getElfNode("effect_YD_zhezhao3")
    self._effect_YD_jiantou = set:getElfNode("effect_YD_jiantou")
    self._effect_button = set:getButtonNode("effect_button")
    self._shader = set:getElfNode("shader")
    self._shader_sb_circle = set:getElfNode("shader_sb_circle")
    self._shader_rect = set:getRectangleNode("shader_rect")
    self._effect = set:getElfNode("effect")
    self._effect_YD_zhezhao1 = set:getElfNode("effect_YD_zhezhao1")
    self._effect_YD_zhezhao2 = set:getElfNode("effect_YD_zhezhao2")
    self._effect_YD_zhezhao3 = set:getElfNode("effect_YD_zhezhao3")
    self._effect_YD_jiantou = set:getElfNode("effect_YD_jiantou")
    self._effect_button = set:getButtonNode("effect_button")
    self._shader = set:getElfNode("shader")
    self._shader_sb_circle = set:getElfNode("shader_sb_circle")
    self._shader_rect = set:getRectangleNode("shader_rect")
    self._tips = set:getElfNode("tips")
    self._tips_portrait = set:getElfNode("tips_portrait")
    self._tips_portrait_pic = set:getElfNode("tips_portrait_pic")
    self._tips_bg2 = set:getElfNode("tips_bg2")
    self._tips_bg = set:getElfNode("tips_bg")
    self._tips_bg_name = set:getLabelNode("tips_bg_name")
    self._tips_bg_info = set:getLabelNode("tips_bg_info")
    self._tips_bg_button = set:getButtonNode("tips_bg_button")
    self._touchBtn = set:getButtonNode("touchBtn")
    self._shader = set:getElfNode("shader")
    self._shader_sb_circle = set:getElfNode("shader_sb_circle")
    self._shader_rect = set:getRectangleNode("shader_rect")
    self._tips = set:getElfNode("tips")
    self._tips_portrait = set:getElfNode("tips_portrait")
    self._tips_portrait_pic = set:getElfNode("tips_portrait_pic")
    self._tips_bg2 = set:getElfNode("tips_bg2")
    self._tips_bg = set:getElfNode("tips_bg")
    self._tips_bg_name = set:getLabelNode("tips_bg_name")
    self._tips_bg_info = set:getLabelNode("tips_bg_info")
    self._tips_bg_button = set:getButtonNode("tips_bg_button")
    self._touchBtn = set:getButtonNode("touchBtn")
--    self._@LieYanMa = set:getElfNode("@LieYanMa")
--    self._@Guide1_0 = set:getElfNode("@Guide1_0")
--    self._@Guide1_1 = set:getElfNode("@Guide1_1")
--    self._@Guide1_2 = set:getElfNode("@Guide1_2")
--    self._@LeiGong = set:getElfNode("@LeiGong")
--    self._@Guide2_0 = set:getElfNode("@Guide2_0")
--    self._@Guide2_1 = set:getElfNode("@Guide2_1")
--    self._@Guide2_2 = set:getElfNode("@Guide2_2")
--    self._@TuoQiaoRenZhe = set:getElfNode("@TuoQiaoRenZhe")
--    self._@Guide3_0 = set:getElfNode("@Guide3_0")
--    self._@Guide3_1 = set:getElfNode("@Guide3_1")
--    self._@Guide3_2 = set:getElfNode("@Guide3_2")
--    self._@JiLaQi = set:getElfNode("@JiLaQi")
--    self._@Guide4_0 = set:getElfNode("@Guide4_0")
--    self._@Guide4_1 = set:getElfNode("@Guide4_1")
--    self._@DaZhao = set:getElfNode("@DaZhao")
--    self._@Guide5_0 = set:getElfNode("@Guide5_0")
--    self._@Guide5_1 = set:getElfNode("@Guide5_1")
--    self._@DaZhao = set:getElfNode("@DaZhao")
--    self._@Guide6_0 = set:getElfNode("@Guide6_0")
--    self._@Guide6_1 = set:getElfNode("@Guide6_1")
--    self._@ChaoMeng = set:getElfNode("@ChaoMeng")
--    self._@Guide7_0 = set:getElfNode("@Guide7_0")
--    self._@Guide7_1 = set:getElfNode("@Guide7_1")
--    self._@black = set:getRectangleNode("@black")
end
--@@@@]]]]

--------------------------------override functions----------------------
function FightGuider:onInit( userData, netData )
	
end

function FightGuider:onBack( userData, netData )
	
end

--------------------------------custom code-----------------------------


--------------------------------class end-------------------------------
require 'framework.basic.MetaHelper'.classDefinitionEnd(FightGuider, "FightGuider")


--------------------------------register--------------------------------
GleeCore:registerLuaController("FightGuider", FightGuider)


