local Config = require "Config"

local LuckyWheel = class(LuaController)

function LuckyWheel:createDocument()
    self._factory:setZipFilePath(Config.COCOS_ZIP_DIR.."LuckyWheel.cocos.zip")
    return self._factory:createDocument("LuckyWheel.cocos")
end

--@@@@[[[[
function LuckyWheel:onInitXML()
	local set = self._set
    self._pet = set:getElfNode("pet")
    self._count = set:getLabelNode("count")
    self._layout1_timer = set:getTimeNode("layout1_timer")
    self._kbg = set:getElfNode("kbg")
    self._kbg_bg = set:getElfNode("kbg_bg")
    self._kbg_item1 = set:getElfNode("kbg_item1")
    self._kbg_item1_bg = set:getElfNode("kbg_item1_bg")
    self._kbg_item1_icon = set:getElfNode("kbg_item1_icon")
    self._kbg_item1_frame = set:getElfNode("kbg_item1_frame")
    self._kbg_item1_count = set:getLabelNode("kbg_item1_count")
    self._kbg_item1_piece = set:getElfNode("kbg_item1_piece")
    self._kbg_item1_hale = set:getElfNode("kbg_item1_hale")
    self._kbg_item1_btn = set:getButtonNode("kbg_item1_btn")
    self._kbg_item2 = set:getElfNode("kbg_item2")
    self._kbg_item2_bg = set:getElfNode("kbg_item2_bg")
    self._kbg_item2_icon = set:getElfNode("kbg_item2_icon")
    self._kbg_item2_frame = set:getElfNode("kbg_item2_frame")
    self._kbg_item2_count = set:getLabelNode("kbg_item2_count")
    self._kbg_item2_piece = set:getElfNode("kbg_item2_piece")
    self._kbg_item2_hale = set:getElfNode("kbg_item2_hale")
    self._kbg_item2_btn = set:getButtonNode("kbg_item2_btn")
    self._kbg_item3 = set:getElfNode("kbg_item3")
    self._kbg_item3_bg = set:getElfNode("kbg_item3_bg")
    self._kbg_item3_icon = set:getElfNode("kbg_item3_icon")
    self._kbg_item3_frame = set:getElfNode("kbg_item3_frame")
    self._kbg_item3_count = set:getLabelNode("kbg_item3_count")
    self._kbg_item3_piece = set:getElfNode("kbg_item3_piece")
    self._kbg_item3_hale = set:getElfNode("kbg_item3_hale")
    self._kbg_item3_btn = set:getButtonNode("kbg_item3_btn")
    self._kbg_item4 = set:getElfNode("kbg_item4")
    self._kbg_item4_bg = set:getElfNode("kbg_item4_bg")
    self._kbg_item4_icon = set:getElfNode("kbg_item4_icon")
    self._kbg_item4_frame = set:getElfNode("kbg_item4_frame")
    self._kbg_item4_count = set:getLabelNode("kbg_item4_count")
    self._kbg_item4_piece = set:getElfNode("kbg_item4_piece")
    self._kbg_item4_hale = set:getElfNode("kbg_item4_hale")
    self._kbg_item4_btn = set:getButtonNode("kbg_item4_btn")
    self._kbg_item5 = set:getElfNode("kbg_item5")
    self._kbg_item5_bg = set:getElfNode("kbg_item5_bg")
    self._kbg_item5_icon = set:getElfNode("kbg_item5_icon")
    self._kbg_item5_frame = set:getElfNode("kbg_item5_frame")
    self._kbg_item5_count = set:getLabelNode("kbg_item5_count")
    self._kbg_item5_piece = set:getElfNode("kbg_item5_piece")
    self._kbg_item5_hale = set:getElfNode("kbg_item5_hale")
    self._kbg_item5_btn = set:getButtonNode("kbg_item5_btn")
    self._kbg_item6 = set:getElfNode("kbg_item6")
    self._kbg_item6_bg = set:getElfNode("kbg_item6_bg")
    self._kbg_item6_icon = set:getElfNode("kbg_item6_icon")
    self._kbg_item6_frame = set:getElfNode("kbg_item6_frame")
    self._kbg_item6_count = set:getLabelNode("kbg_item6_count")
    self._kbg_item6_piece = set:getElfNode("kbg_item6_piece")
    self._kbg_item6_hale = set:getElfNode("kbg_item6_hale")
    self._kbg_item6_btn = set:getButtonNode("kbg_item6_btn")
    self._kbg_item7 = set:getElfNode("kbg_item7")
    self._kbg_item7_bg = set:getElfNode("kbg_item7_bg")
    self._kbg_item7_icon = set:getElfNode("kbg_item7_icon")
    self._kbg_item7_frame = set:getElfNode("kbg_item7_frame")
    self._kbg_item7_count = set:getLabelNode("kbg_item7_count")
    self._kbg_item7_piece = set:getElfNode("kbg_item7_piece")
    self._kbg_item7_hale = set:getElfNode("kbg_item7_hale")
    self._kbg_item7_btn = set:getButtonNode("kbg_item7_btn")
    self._kbg_item8 = set:getElfNode("kbg_item8")
    self._kbg_item8_bg = set:getElfNode("kbg_item8_bg")
    self._kbg_item8_icon = set:getElfNode("kbg_item8_icon")
    self._kbg_item8_frame = set:getElfNode("kbg_item8_frame")
    self._kbg_item8_count = set:getLabelNode("kbg_item8_count")
    self._kbg_item8_piece = set:getElfNode("kbg_item8_piece")
    self._kbg_item8_hale = set:getElfNode("kbg_item8_hale")
    self._kbg_item8_btn = set:getButtonNode("kbg_item8_btn")
    self._kbg_item9 = set:getElfNode("kbg_item9")
    self._kbg_item9_bg = set:getElfNode("kbg_item9_bg")
    self._kbg_item9_icon = set:getElfNode("kbg_item9_icon")
    self._kbg_item9_frame = set:getElfNode("kbg_item9_frame")
    self._kbg_item9_count = set:getLabelNode("kbg_item9_count")
    self._kbg_item9_piece = set:getElfNode("kbg_item9_piece")
    self._kbg_item9_hale = set:getElfNode("kbg_item9_hale")
    self._kbg_item9_btn = set:getButtonNode("kbg_item9_btn")
    self._kbg_item10 = set:getElfNode("kbg_item10")
    self._kbg_item10_bg = set:getElfNode("kbg_item10_bg")
    self._kbg_item10_icon = set:getElfNode("kbg_item10_icon")
    self._kbg_item10_frame = set:getElfNode("kbg_item10_frame")
    self._kbg_item10_count = set:getLabelNode("kbg_item10_count")
    self._kbg_item10_piece = set:getElfNode("kbg_item10_piece")
    self._kbg_item10_hale = set:getElfNode("kbg_item10_hale")
    self._kbg_item10_btn = set:getButtonNode("kbg_item10_btn")
    self._kbg_item11 = set:getElfNode("kbg_item11")
    self._kbg_item11_bg = set:getElfNode("kbg_item11_bg")
    self._kbg_item11_icon = set:getElfNode("kbg_item11_icon")
    self._kbg_item11_frame = set:getElfNode("kbg_item11_frame")
    self._kbg_item11_count = set:getLabelNode("kbg_item11_count")
    self._kbg_item11_piece = set:getElfNode("kbg_item11_piece")
    self._kbg_item11_hale = set:getElfNode("kbg_item11_hale")
    self._kbg_item11_btn = set:getButtonNode("kbg_item11_btn")
    self._kbg_item12 = set:getElfNode("kbg_item12")
    self._kbg_item12_bg = set:getElfNode("kbg_item12_bg")
    self._kbg_item12_icon = set:getElfNode("kbg_item12_icon")
    self._kbg_item12_frame = set:getElfNode("kbg_item12_frame")
    self._kbg_item12_count = set:getLabelNode("kbg_item12_count")
    self._kbg_item12_piece = set:getElfNode("kbg_item12_piece")
    self._kbg_item12_hale = set:getElfNode("kbg_item12_hale")
    self._kbg_item12_btn = set:getButtonNode("kbg_item12_btn")
    self._kbg_btnRefresh = set:getButtonNode("kbg_btnRefresh")
    self._kbg_btnRefresh_pet = set:getElfNode("kbg_btnRefresh_pet")
    self._kbg_btnRefresh_layout_count = set:getLabelNode("kbg_btnRefresh_layout_count")
    self._btnTurn1 = set:getButtonNode("btnTurn1")
    self._btnTurn1_layout = set:getLinearLayoutNode("btnTurn1_layout")
    self._btnTurn1_layout_count = set:getLabelNode("btnTurn1_layout_count")
    self._btnTurn1_free = set:getLabelNode("btnTurn1_free")
    self._btnTurn10 = set:getButtonNode("btnTurn10")
    self._btnTurn10_layout_count = set:getLabelNode("btnTurn10_layout_count")
    self._shield = set:getShieldNode("shield")
--    self._@view = set:getElfNode("@view")
end
--@@@@]]]]

--------------------------------override functions----------------------
function LuckyWheel:onInit( userData, netData )
	
end

function LuckyWheel:onBack( userData, netData )
	
end

--------------------------------custom code-----------------------------


--------------------------------class end-------------------------------
require 'framework.basic.MetaHelper'.classDefinitionEnd(LuckyWheel, "LuckyWheel")


--------------------------------register--------------------------------
GleeCore:registerLuaController("LuckyWheel", LuckyWheel)


